// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v5.29.3
// source: perpx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import Long from "long";

export const protobufPackage = "perpx";

export interface TelegramLoginRequest {
  /** Telegram 提供的 initData */
  initData: string;
}

export interface LoginResponse {
  /** JWT Token */
  token: string;
}

export interface ProfileRequest {
  /** JWT Token */
  token: string;
}

export interface ProfileResponse {
  telegramId: string;
  telegramName: string;
  maxStrategies: number;
  active: boolean;
  subscriptionStart?: string | undefined;
  subscriptionEnd?: string | undefined;
  email?: string | undefined;
}

function createBaseTelegramLoginRequest(): TelegramLoginRequest {
  return { initData: "" };
}

export const TelegramLoginRequest: MessageFns<TelegramLoginRequest> = {
  encode(message: TelegramLoginRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.initData !== "") {
      writer.uint32(10).string(message.initData);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TelegramLoginRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTelegramLoginRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.initData = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TelegramLoginRequest {
    return { initData: isSet(object.initData) ? globalThis.String(object.initData) : "" };
  },

  toJSON(message: TelegramLoginRequest): unknown {
    const obj: any = {};
    if (message.initData !== "") {
      obj.initData = message.initData;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TelegramLoginRequest>, I>>(base?: I): TelegramLoginRequest {
    return TelegramLoginRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TelegramLoginRequest>, I>>(object: I): TelegramLoginRequest {
    const message = createBaseTelegramLoginRequest();
    message.initData = object.initData ?? "";
    return message;
  },
};

function createBaseLoginResponse(): LoginResponse {
  return { token: "" };
}

export const LoginResponse: MessageFns<LoginResponse> = {
  encode(message: LoginResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoginResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoginResponse {
    return { token: isSet(object.token) ? globalThis.String(object.token) : "" };
  },

  toJSON(message: LoginResponse): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoginResponse>, I>>(base?: I): LoginResponse {
    return LoginResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoginResponse>, I>>(object: I): LoginResponse {
    const message = createBaseLoginResponse();
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseProfileRequest(): ProfileRequest {
  return { token: "" };
}

export const ProfileRequest: MessageFns<ProfileRequest> = {
  encode(message: ProfileRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProfileRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProfileRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProfileRequest {
    return { token: isSet(object.token) ? globalThis.String(object.token) : "" };
  },

  toJSON(message: ProfileRequest): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProfileRequest>, I>>(base?: I): ProfileRequest {
    return ProfileRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProfileRequest>, I>>(object: I): ProfileRequest {
    const message = createBaseProfileRequest();
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseProfileResponse(): ProfileResponse {
  return {
    telegramId: "",
    telegramName: "",
    maxStrategies: 0,
    active: false,
    subscriptionStart: undefined,
    subscriptionEnd: undefined,
    email: undefined,
  };
}

export const ProfileResponse: MessageFns<ProfileResponse> = {
  encode(message: ProfileResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.telegramId !== "") {
      writer.uint32(10).string(message.telegramId);
    }
    if (message.telegramName !== "") {
      writer.uint32(18).string(message.telegramName);
    }
    if (message.maxStrategies !== 0) {
      writer.uint32(24).int32(message.maxStrategies);
    }
    if (message.active !== false) {
      writer.uint32(32).bool(message.active);
    }
    if (message.subscriptionStart !== undefined) {
      writer.uint32(42).string(message.subscriptionStart);
    }
    if (message.subscriptionEnd !== undefined) {
      writer.uint32(50).string(message.subscriptionEnd);
    }
    if (message.email !== undefined) {
      writer.uint32(58).string(message.email);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProfileResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProfileResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.telegramId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.telegramName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.maxStrategies = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.active = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.subscriptionStart = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.subscriptionEnd = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.email = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProfileResponse {
    return {
      telegramId: isSet(object.telegramId) ? globalThis.String(object.telegramId) : "",
      telegramName: isSet(object.telegramName) ? globalThis.String(object.telegramName) : "",
      maxStrategies: isSet(object.maxStrategies) ? globalThis.Number(object.maxStrategies) : 0,
      active: isSet(object.active) ? globalThis.Boolean(object.active) : false,
      subscriptionStart: isSet(object.subscriptionStart) ? globalThis.String(object.subscriptionStart) : undefined,
      subscriptionEnd: isSet(object.subscriptionEnd) ? globalThis.String(object.subscriptionEnd) : undefined,
      email: isSet(object.email) ? globalThis.String(object.email) : undefined,
    };
  },

  toJSON(message: ProfileResponse): unknown {
    const obj: any = {};
    if (message.telegramId !== "") {
      obj.telegramId = message.telegramId;
    }
    if (message.telegramName !== "") {
      obj.telegramName = message.telegramName;
    }
    if (message.maxStrategies !== 0) {
      obj.maxStrategies = Math.round(message.maxStrategies);
    }
    if (message.active !== false) {
      obj.active = message.active;
    }
    if (message.subscriptionStart !== undefined) {
      obj.subscriptionStart = message.subscriptionStart;
    }
    if (message.subscriptionEnd !== undefined) {
      obj.subscriptionEnd = message.subscriptionEnd;
    }
    if (message.email !== undefined) {
      obj.email = message.email;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProfileResponse>, I>>(base?: I): ProfileResponse {
    return ProfileResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProfileResponse>, I>>(object: I): ProfileResponse {
    const message = createBaseProfileResponse();
    message.telegramId = object.telegramId ?? "";
    message.telegramName = object.telegramName ?? "";
    message.maxStrategies = object.maxStrategies ?? 0;
    message.active = object.active ?? false;
    message.subscriptionStart = object.subscriptionStart ?? undefined;
    message.subscriptionEnd = object.subscriptionEnd ?? undefined;
    message.email = object.email ?? undefined;
    return message;
  },
};

export interface PerpxService {
  LoginWithTelegram(request: TelegramLoginRequest): Promise<LoginResponse>;
  GetProfile(request: ProfileRequest): Promise<ProfileResponse>;
}

export const PerpxServiceServiceName = "perpx.PerpxService";
export class PerpxServiceClientImpl implements PerpxService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || PerpxServiceServiceName;
    this.rpc = rpc;
    this.LoginWithTelegram = this.LoginWithTelegram.bind(this);
    this.GetProfile = this.GetProfile.bind(this);
  }
  LoginWithTelegram(request: TelegramLoginRequest): Promise<LoginResponse> {
    const data = TelegramLoginRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "LoginWithTelegram", data);
    return promise.then((data) => LoginResponse.decode(new BinaryReader(data)));
  }

  GetProfile(request: ProfileRequest): Promise<ProfileResponse> {
    const data = ProfileRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetProfile", data);
    return promise.then((data) => ProfileResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
